### ISSUE TITLE
Why take values greater than 20?

### ISSUE THREAD

**Issue by cheziwei2020** [JLDeng/ST-Norm#2]
Hi, thanks for your work.
Why only values greater than 20 are used in MAPE?

def MAPE(v, v_):
    greater_than_20 = v > 20
    v = v[greater_than_20]
    v_ = v_[greater_than_20]
    return np.mean(np.abs(v_ - v) / (v))

Thank you very much!

**Comment by JLDeng** [comment]
MAPE takes v as the denominator. So a small v will lead to large variance in MAPE.
